//
// WARNING! All changes made in this file will be lost!
// Created from 'scheme.tl' by 'codegen_proto.py'
//
//  Copyright (c) 2017, https://github.com/xxxxx
//  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: schema.tl.handshake.proto

package mtproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// /////////////////////////////////////////////////////////////////////////////
// Server_DH_Params <--
//   - TL_server_DH_params_fail
//   - TL_server_DH_params_ok
type Server_DH_Params_Data struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Nonce           []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce     []byte                 `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	NewNonceHash    []byte                 `protobuf:"bytes,3,opt,name=new_nonce_hash,json=newNonceHash,proto3" json:"new_nonce_hash,omitempty"`
	EncryptedAnswer string                 `protobuf:"bytes,4,opt,name=encrypted_answer,json=encryptedAnswer,proto3" json:"encrypted_answer,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Server_DH_Params_Data) Reset() {
	*x = Server_DH_Params_Data{}
	mi := &file_schema_tl_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_DH_Params_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_DH_Params_Data) ProtoMessage() {}

func (x *Server_DH_Params_Data) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_DH_Params_Data.ProtoReflect.Descriptor instead.
func (*Server_DH_Params_Data) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *Server_DH_Params_Data) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Server_DH_Params_Data) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *Server_DH_Params_Data) GetNewNonceHash() []byte {
	if x != nil {
		return x.NewNonceHash
	}
	return nil
}

func (x *Server_DH_Params_Data) GetEncryptedAnswer() string {
	if x != nil {
		return x.EncryptedAnswer
	}
	return ""
}

type Server_DH_Params struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data          *Server_DH_Params_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_DH_Params) Reset() {
	*x = Server_DH_Params{}
	mi := &file_schema_tl_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_DH_Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_DH_Params) ProtoMessage() {}

func (x *Server_DH_Params) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_DH_Params.ProtoReflect.Descriptor instead.
func (*Server_DH_Params) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *Server_DH_Params) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *Server_DH_Params) GetData() *Server_DH_Params_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// server_DH_params_fail#79cb045d nonce:int128 server_nonce:int128 new_nonce_hash:int128 = Server_DH_Params;
type TLServer_DHParamsFail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Server_DH_Params_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLServer_DHParamsFail) Reset() {
	*x = TLServer_DHParamsFail{}
	mi := &file_schema_tl_handshake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLServer_DHParamsFail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLServer_DHParamsFail) ProtoMessage() {}

func (x *TLServer_DHParamsFail) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLServer_DHParamsFail.ProtoReflect.Descriptor instead.
func (*TLServer_DHParamsFail) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{2}
}

func (x *TLServer_DHParamsFail) GetData() *Server_DH_Params_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// server_DH_params_ok#d0e8075c nonce:int128 server_nonce:int128 encrypted_answer:string = Server_DH_Params;
type TLServer_DHParamsOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Server_DH_Params_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLServer_DHParamsOk) Reset() {
	*x = TLServer_DHParamsOk{}
	mi := &file_schema_tl_handshake_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLServer_DHParamsOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLServer_DHParamsOk) ProtoMessage() {}

func (x *TLServer_DHParamsOk) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLServer_DHParamsOk.ProtoReflect.Descriptor instead.
func (*TLServer_DHParamsOk) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{3}
}

func (x *TLServer_DHParamsOk) GetData() *Server_DH_Params_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// Server_DH_inner_data <--
//   - TL_server_DH_inner_data
type Server_DHInnerData_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce   []byte                 `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	G             int32                  `protobuf:"varint,3,opt,name=g,proto3" json:"g,omitempty"`
	DhPrime       string                 `protobuf:"bytes,4,opt,name=dh_prime,json=dhPrime,proto3" json:"dh_prime,omitempty"`
	GA            string                 `protobuf:"bytes,5,opt,name=g_a,json=gA,proto3" json:"g_a,omitempty"`
	ServerTime    int32                  `protobuf:"varint,6,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_DHInnerData_Data) Reset() {
	*x = Server_DHInnerData_Data{}
	mi := &file_schema_tl_handshake_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_DHInnerData_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_DHInnerData_Data) ProtoMessage() {}

func (x *Server_DHInnerData_Data) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_DHInnerData_Data.ProtoReflect.Descriptor instead.
func (*Server_DHInnerData_Data) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{4}
}

func (x *Server_DHInnerData_Data) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Server_DHInnerData_Data) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *Server_DHInnerData_Data) GetG() int32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *Server_DHInnerData_Data) GetDhPrime() string {
	if x != nil {
		return x.DhPrime
	}
	return ""
}

func (x *Server_DHInnerData_Data) GetGA() string {
	if x != nil {
		return x.GA
	}
	return ""
}

func (x *Server_DHInnerData_Data) GetServerTime() int32 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type Server_DHInnerData struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Constructor   TLConstructor            `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data          *Server_DHInnerData_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_DHInnerData) Reset() {
	*x = Server_DHInnerData{}
	mi := &file_schema_tl_handshake_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_DHInnerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_DHInnerData) ProtoMessage() {}

func (x *Server_DHInnerData) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_DHInnerData.ProtoReflect.Descriptor instead.
func (*Server_DHInnerData) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{5}
}

func (x *Server_DHInnerData) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *Server_DHInnerData) GetData() *Server_DHInnerData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// server_DH_inner_data#b5890dba nonce:int128 server_nonce:int128 g:int dh_prime:string g_a:string server_time:int = Server_DH_inner_data;
type TLServer_DHInnerData struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Data          *Server_DHInnerData_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLServer_DHInnerData) Reset() {
	*x = TLServer_DHInnerData{}
	mi := &file_schema_tl_handshake_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLServer_DHInnerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLServer_DHInnerData) ProtoMessage() {}

func (x *TLServer_DHInnerData) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLServer_DHInnerData.ProtoReflect.Descriptor instead.
func (*TLServer_DHInnerData) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{6}
}

func (x *TLServer_DHInnerData) GetData() *Server_DHInnerData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// Client_DH_Inner_Data <--
//   - TL_client_DH_inner_data
type Client_DH_Inner_Data_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce   []byte                 `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	RetryId       int64                  `protobuf:"varint,3,opt,name=retry_id,json=retryId,proto3" json:"retry_id,omitempty"`
	GB            string                 `protobuf:"bytes,4,opt,name=g_b,json=gB,proto3" json:"g_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client_DH_Inner_Data_Data) Reset() {
	*x = Client_DH_Inner_Data_Data{}
	mi := &file_schema_tl_handshake_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_DH_Inner_Data_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_DH_Inner_Data_Data) ProtoMessage() {}

func (x *Client_DH_Inner_Data_Data) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_DH_Inner_Data_Data.ProtoReflect.Descriptor instead.
func (*Client_DH_Inner_Data_Data) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{7}
}

func (x *Client_DH_Inner_Data_Data) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Client_DH_Inner_Data_Data) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *Client_DH_Inner_Data_Data) GetRetryId() int64 {
	if x != nil {
		return x.RetryId
	}
	return 0
}

func (x *Client_DH_Inner_Data_Data) GetGB() string {
	if x != nil {
		return x.GB
	}
	return ""
}

type Client_DH_Inner_Data struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Constructor   TLConstructor              `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data          *Client_DH_Inner_Data_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client_DH_Inner_Data) Reset() {
	*x = Client_DH_Inner_Data{}
	mi := &file_schema_tl_handshake_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_DH_Inner_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_DH_Inner_Data) ProtoMessage() {}

func (x *Client_DH_Inner_Data) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_DH_Inner_Data.ProtoReflect.Descriptor instead.
func (*Client_DH_Inner_Data) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{8}
}

func (x *Client_DH_Inner_Data) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *Client_DH_Inner_Data) GetData() *Client_DH_Inner_Data_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// client_DH_inner_data#6643b654 nonce:int128 server_nonce:int128 retry_id:long g_b:string = Client_DH_Inner_Data;
type TLClient_DHInnerData struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          *Client_DH_Inner_Data_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLClient_DHInnerData) Reset() {
	*x = TLClient_DHInnerData{}
	mi := &file_schema_tl_handshake_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLClient_DHInnerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLClient_DHInnerData) ProtoMessage() {}

func (x *TLClient_DHInnerData) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLClient_DHInnerData.ProtoReflect.Descriptor instead.
func (*TLClient_DHInnerData) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{9}
}

func (x *TLClient_DHInnerData) GetData() *Client_DH_Inner_Data_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// Set_client_DH_params_answer <--
//   - TL_dh_gen_ok
//   - TL_dh_gen_retry
//   - TL_dh_gen_fail
type SetClient_DHParamsAnswer_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce   []byte                 `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	NewNonceHash1 []byte                 `protobuf:"bytes,3,opt,name=new_nonce_hash1,json=newNonceHash1,proto3" json:"new_nonce_hash1,omitempty"`
	NewNonceHash2 []byte                 `protobuf:"bytes,4,opt,name=new_nonce_hash2,json=newNonceHash2,proto3" json:"new_nonce_hash2,omitempty"`
	NewNonceHash3 []byte                 `protobuf:"bytes,5,opt,name=new_nonce_hash3,json=newNonceHash3,proto3" json:"new_nonce_hash3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClient_DHParamsAnswer_Data) Reset() {
	*x = SetClient_DHParamsAnswer_Data{}
	mi := &file_schema_tl_handshake_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClient_DHParamsAnswer_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClient_DHParamsAnswer_Data) ProtoMessage() {}

func (x *SetClient_DHParamsAnswer_Data) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClient_DHParamsAnswer_Data.ProtoReflect.Descriptor instead.
func (*SetClient_DHParamsAnswer_Data) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{10}
}

func (x *SetClient_DHParamsAnswer_Data) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *SetClient_DHParamsAnswer_Data) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *SetClient_DHParamsAnswer_Data) GetNewNonceHash1() []byte {
	if x != nil {
		return x.NewNonceHash1
	}
	return nil
}

func (x *SetClient_DHParamsAnswer_Data) GetNewNonceHash2() []byte {
	if x != nil {
		return x.NewNonceHash2
	}
	return nil
}

func (x *SetClient_DHParamsAnswer_Data) GetNewNonceHash3() []byte {
	if x != nil {
		return x.NewNonceHash3
	}
	return nil
}

type SetClient_DHParamsAnswer struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Constructor   TLConstructor                  `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data          *SetClient_DHParamsAnswer_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClient_DHParamsAnswer) Reset() {
	*x = SetClient_DHParamsAnswer{}
	mi := &file_schema_tl_handshake_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClient_DHParamsAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClient_DHParamsAnswer) ProtoMessage() {}

func (x *SetClient_DHParamsAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClient_DHParamsAnswer.ProtoReflect.Descriptor instead.
func (*SetClient_DHParamsAnswer) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{11}
}

func (x *SetClient_DHParamsAnswer) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *SetClient_DHParamsAnswer) GetData() *SetClient_DHParamsAnswer_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// dh_gen_ok#3bcbf734 nonce:int128 server_nonce:int128 new_nonce_hash1:int128 = Set_client_DH_params_answer;
type TLDhGenOk struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Data          *SetClient_DHParamsAnswer_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLDhGenOk) Reset() {
	*x = TLDhGenOk{}
	mi := &file_schema_tl_handshake_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLDhGenOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLDhGenOk) ProtoMessage() {}

func (x *TLDhGenOk) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLDhGenOk.ProtoReflect.Descriptor instead.
func (*TLDhGenOk) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{12}
}

func (x *TLDhGenOk) GetData() *SetClient_DHParamsAnswer_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// dh_gen_retry#46dc1fb9 nonce:int128 server_nonce:int128 new_nonce_hash2:int128 = Set_client_DH_params_answer;
type TLDhGenRetry struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Data          *SetClient_DHParamsAnswer_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLDhGenRetry) Reset() {
	*x = TLDhGenRetry{}
	mi := &file_schema_tl_handshake_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLDhGenRetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLDhGenRetry) ProtoMessage() {}

func (x *TLDhGenRetry) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLDhGenRetry.ProtoReflect.Descriptor instead.
func (*TLDhGenRetry) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{13}
}

func (x *TLDhGenRetry) GetData() *SetClient_DHParamsAnswer_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// dh_gen_fail#a69dae02 nonce:int128 server_nonce:int128 new_nonce_hash3:int128 = Set_client_DH_params_answer;
type TLDhGenFail struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Data          *SetClient_DHParamsAnswer_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLDhGenFail) Reset() {
	*x = TLDhGenFail{}
	mi := &file_schema_tl_handshake_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLDhGenFail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLDhGenFail) ProtoMessage() {}

func (x *TLDhGenFail) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLDhGenFail.ProtoReflect.Descriptor instead.
func (*TLDhGenFail) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{14}
}

func (x *TLDhGenFail) GetData() *SetClient_DHParamsAnswer_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// DestroyAuthKeyRes <--
//   - TL_destroy_auth_key_ok
//   - TL_destroy_auth_key_none
//   - TL_destroy_auth_key_fail
type DestroyAuthKeyRes_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyAuthKeyRes_Data) Reset() {
	*x = DestroyAuthKeyRes_Data{}
	mi := &file_schema_tl_handshake_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyAuthKeyRes_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyAuthKeyRes_Data) ProtoMessage() {}

func (x *DestroyAuthKeyRes_Data) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyAuthKeyRes_Data.ProtoReflect.Descriptor instead.
func (*DestroyAuthKeyRes_Data) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{15}
}

type DestroyAuthKeyRes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Constructor   TLConstructor           `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data          *DestroyAuthKeyRes_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyAuthKeyRes) Reset() {
	*x = DestroyAuthKeyRes{}
	mi := &file_schema_tl_handshake_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyAuthKeyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyAuthKeyRes) ProtoMessage() {}

func (x *DestroyAuthKeyRes) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyAuthKeyRes.ProtoReflect.Descriptor instead.
func (*DestroyAuthKeyRes) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{16}
}

func (x *DestroyAuthKeyRes) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *DestroyAuthKeyRes) GetData() *DestroyAuthKeyRes_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// destroy_auth_key_ok#f660e1d4 = DestroyAuthKeyRes;
type TLDestroyAuthKeyOk struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          *DestroyAuthKeyRes_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLDestroyAuthKeyOk) Reset() {
	*x = TLDestroyAuthKeyOk{}
	mi := &file_schema_tl_handshake_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLDestroyAuthKeyOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLDestroyAuthKeyOk) ProtoMessage() {}

func (x *TLDestroyAuthKeyOk) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLDestroyAuthKeyOk.ProtoReflect.Descriptor instead.
func (*TLDestroyAuthKeyOk) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{17}
}

func (x *TLDestroyAuthKeyOk) GetData() *DestroyAuthKeyRes_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// destroy_auth_key_none#0a9f2259 = DestroyAuthKeyRes;
type TLDestroyAuthKeyNone struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          *DestroyAuthKeyRes_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLDestroyAuthKeyNone) Reset() {
	*x = TLDestroyAuthKeyNone{}
	mi := &file_schema_tl_handshake_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLDestroyAuthKeyNone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLDestroyAuthKeyNone) ProtoMessage() {}

func (x *TLDestroyAuthKeyNone) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLDestroyAuthKeyNone.ProtoReflect.Descriptor instead.
func (*TLDestroyAuthKeyNone) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{18}
}

func (x *TLDestroyAuthKeyNone) GetData() *DestroyAuthKeyRes_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// destroy_auth_key_fail#ea109b13 = DestroyAuthKeyRes;
type TLDestroyAuthKeyFail struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          *DestroyAuthKeyRes_Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLDestroyAuthKeyFail) Reset() {
	*x = TLDestroyAuthKeyFail{}
	mi := &file_schema_tl_handshake_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLDestroyAuthKeyFail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLDestroyAuthKeyFail) ProtoMessage() {}

func (x *TLDestroyAuthKeyFail) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLDestroyAuthKeyFail.ProtoReflect.Descriptor instead.
func (*TLDestroyAuthKeyFail) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{19}
}

func (x *TLDestroyAuthKeyFail) GetData() *DestroyAuthKeyRes_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// ResPQ <--
//   - TL_resPQ
type ResPQ_Data struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Nonce                       []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce                 []byte                 `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	Pq                          string                 `protobuf:"bytes,3,opt,name=pq,proto3" json:"pq,omitempty"`
	ServerPublicKeyFingerprints []int64                `protobuf:"varint,4,rep,packed,name=server_public_key_fingerprints,json=serverPublicKeyFingerprints,proto3" json:"server_public_key_fingerprints,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ResPQ_Data) Reset() {
	*x = ResPQ_Data{}
	mi := &file_schema_tl_handshake_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResPQ_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResPQ_Data) ProtoMessage() {}

func (x *ResPQ_Data) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResPQ_Data.ProtoReflect.Descriptor instead.
func (*ResPQ_Data) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{20}
}

func (x *ResPQ_Data) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ResPQ_Data) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *ResPQ_Data) GetPq() string {
	if x != nil {
		return x.Pq
	}
	return ""
}

func (x *ResPQ_Data) GetServerPublicKeyFingerprints() []int64 {
	if x != nil {
		return x.ServerPublicKeyFingerprints
	}
	return nil
}

type ResPQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data          *ResPQ_Data            `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResPQ) Reset() {
	*x = ResPQ{}
	mi := &file_schema_tl_handshake_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResPQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResPQ) ProtoMessage() {}

func (x *ResPQ) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResPQ.ProtoReflect.Descriptor instead.
func (*ResPQ) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{21}
}

func (x *ResPQ) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *ResPQ) GetData() *ResPQ_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// resPQ#05162463 nonce:int128 server_nonce:int128 pq:string server_public_key_fingerprints:Vector<long> = ResPQ;
type TLResPQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ResPQ_Data            `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLResPQ) Reset() {
	*x = TLResPQ{}
	mi := &file_schema_tl_handshake_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLResPQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLResPQ) ProtoMessage() {}

func (x *TLResPQ) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLResPQ.ProtoReflect.Descriptor instead.
func (*TLResPQ) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{22}
}

func (x *TLResPQ) GetData() *ResPQ_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// P_Q_inner_data <--
//   - TL_p_q_inner_data
type P_QInnerData_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pq            string                 `protobuf:"bytes,1,opt,name=pq,proto3" json:"pq,omitempty"`
	P             string                 `protobuf:"bytes,2,opt,name=p,proto3" json:"p,omitempty"`
	Q             string                 `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce   []byte                 `protobuf:"bytes,5,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	NewNonce      []byte                 `protobuf:"bytes,6,opt,name=new_nonce,json=newNonce,proto3" json:"new_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P_QInnerData_Data) Reset() {
	*x = P_QInnerData_Data{}
	mi := &file_schema_tl_handshake_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P_QInnerData_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P_QInnerData_Data) ProtoMessage() {}

func (x *P_QInnerData_Data) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P_QInnerData_Data.ProtoReflect.Descriptor instead.
func (*P_QInnerData_Data) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{23}
}

func (x *P_QInnerData_Data) GetPq() string {
	if x != nil {
		return x.Pq
	}
	return ""
}

func (x *P_QInnerData_Data) GetP() string {
	if x != nil {
		return x.P
	}
	return ""
}

func (x *P_QInnerData_Data) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *P_QInnerData_Data) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *P_QInnerData_Data) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *P_QInnerData_Data) GetNewNonce() []byte {
	if x != nil {
		return x.NewNonce
	}
	return nil
}

type P_QInnerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data          *P_QInnerData_Data     `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P_QInnerData) Reset() {
	*x = P_QInnerData{}
	mi := &file_schema_tl_handshake_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P_QInnerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P_QInnerData) ProtoMessage() {}

func (x *P_QInnerData) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P_QInnerData.ProtoReflect.Descriptor instead.
func (*P_QInnerData) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{24}
}

func (x *P_QInnerData) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *P_QInnerData) GetData() *P_QInnerData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// p_q_inner_data#83c95aec pq:string p:string q:string nonce:int128 server_nonce:int128 new_nonce:int256 = P_Q_inner_data;
type TLPQInnerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *P_QInnerData_Data     `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLPQInnerData) Reset() {
	*x = TLPQInnerData{}
	mi := &file_schema_tl_handshake_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLPQInnerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLPQInnerData) ProtoMessage() {}

func (x *TLPQInnerData) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_handshake_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLPQInnerData.ProtoReflect.Descriptor instead.
func (*TLPQInnerData) Descriptor() ([]byte, []int) {
	return file_schema_tl_handshake_proto_rawDescGZIP(), []int{25}
}

func (x *TLPQInnerData) GetData() *P_QInnerData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_schema_tl_handshake_proto protoreflect.FileDescriptor

const file_schema_tl_handshake_proto_rawDesc = "" +
	"\n" +
	"\x19schema.tl.handshake.proto\x12\amtproto\x1a\x15schema.tl.crc32.proto\"\xa1\x01\n" +
	"\x15Server_DH_Params_Data\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12!\n" +
	"\fserver_nonce\x18\x02 \x01(\fR\vserverNonce\x12$\n" +
	"\x0enew_nonce_hash\x18\x03 \x01(\fR\fnewNonceHash\x12)\n" +
	"\x10encrypted_answer\x18\x04 \x01(\tR\x0fencryptedAnswer\"\x80\x01\n" +
	"\x10Server_DH_Params\x128\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x16.mtproto.TLConstructorR\vconstructor\x122\n" +
	"\x04Data\x18\x02 \x01(\v2\x1e.mtproto.Server_DH_Params_DataR\x04Data\"N\n" +
	"\x18TL_server_DH_params_fail\x122\n" +
	"\x04Data\x18\x02 \x01(\v2\x1e.mtproto.Server_DH_Params_DataR\x04Data\"L\n" +
	"\x16TL_server_DH_params_ok\x122\n" +
	"\x04Data\x18\x02 \x01(\v2\x1e.mtproto.Server_DH_Params_DataR\x04Data\"\xaf\x01\n" +
	"\x19Server_DH_inner_data_Data\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12!\n" +
	"\fserver_nonce\x18\x02 \x01(\fR\vserverNonce\x12\f\n" +
	"\x01g\x18\x03 \x01(\x05R\x01g\x12\x19\n" +
	"\bdh_prime\x18\x04 \x01(\tR\adhPrime\x12\x0f\n" +
	"\x03g_a\x18\x05 \x01(\tR\x02gA\x12\x1f\n" +
	"\vserver_time\x18\x06 \x01(\x05R\n" +
	"serverTime\"\x88\x01\n" +
	"\x14Server_DH_inner_data\x128\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x16.mtproto.TLConstructorR\vconstructor\x126\n" +
	"\x04Data\x18\x02 \x01(\v2\".mtproto.Server_DH_inner_data_DataR\x04Data\"Q\n" +
	"\x17TL_server_DH_inner_data\x126\n" +
	"\x04Data\x18\x02 \x01(\v2\".mtproto.Server_DH_inner_data_DataR\x04Data\"\x80\x01\n" +
	"\x19Client_DH_Inner_Data_Data\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12!\n" +
	"\fserver_nonce\x18\x02 \x01(\fR\vserverNonce\x12\x19\n" +
	"\bretry_id\x18\x03 \x01(\x03R\aretryId\x12\x0f\n" +
	"\x03g_b\x18\x04 \x01(\tR\x02gB\"\x88\x01\n" +
	"\x14Client_DH_Inner_Data\x128\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x16.mtproto.TLConstructorR\vconstructor\x126\n" +
	"\x04Data\x18\x02 \x01(\v2\".mtproto.Client_DH_Inner_Data_DataR\x04Data\"Q\n" +
	"\x17TL_client_DH_inner_data\x126\n" +
	"\x04Data\x18\x02 \x01(\v2\".mtproto.Client_DH_Inner_Data_DataR\x04Data\"\xd3\x01\n" +
	" Set_client_DH_params_answer_Data\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12!\n" +
	"\fserver_nonce\x18\x02 \x01(\fR\vserverNonce\x12&\n" +
	"\x0fnew_nonce_hash1\x18\x03 \x01(\fR\rnewNonceHash1\x12&\n" +
	"\x0fnew_nonce_hash2\x18\x04 \x01(\fR\rnewNonceHash2\x12&\n" +
	"\x0fnew_nonce_hash3\x18\x05 \x01(\fR\rnewNonceHash3\"\x96\x01\n" +
	"\x1bSet_client_DH_params_answer\x128\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x16.mtproto.TLConstructorR\vconstructor\x12=\n" +
	"\x04Data\x18\x02 \x01(\v2).mtproto.Set_client_DH_params_answer_DataR\x04Data\"M\n" +
	"\fTL_dh_gen_ok\x12=\n" +
	"\x04Data\x18\x02 \x01(\v2).mtproto.Set_client_DH_params_answer_DataR\x04Data\"P\n" +
	"\x0fTL_dh_gen_retry\x12=\n" +
	"\x04Data\x18\x02 \x01(\v2).mtproto.Set_client_DH_params_answer_DataR\x04Data\"O\n" +
	"\x0eTL_dh_gen_fail\x12=\n" +
	"\x04Data\x18\x02 \x01(\v2).mtproto.Set_client_DH_params_answer_DataR\x04Data\"\x18\n" +
	"\x16DestroyAuthKeyRes_Data\"\x82\x01\n" +
	"\x11DestroyAuthKeyRes\x128\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x16.mtproto.TLConstructorR\vconstructor\x123\n" +
	"\x04Data\x18\x02 \x01(\v2\x1f.mtproto.DestroyAuthKeyRes_DataR\x04Data\"M\n" +
	"\x16TL_destroy_auth_key_ok\x123\n" +
	"\x04Data\x18\x02 \x01(\v2\x1f.mtproto.DestroyAuthKeyRes_DataR\x04Data\"O\n" +
	"\x18TL_destroy_auth_key_none\x123\n" +
	"\x04Data\x18\x02 \x01(\v2\x1f.mtproto.DestroyAuthKeyRes_DataR\x04Data\"O\n" +
	"\x18TL_destroy_auth_key_fail\x123\n" +
	"\x04Data\x18\x02 \x01(\v2\x1f.mtproto.DestroyAuthKeyRes_DataR\x04Data\"\x9a\x01\n" +
	"\n" +
	"ResPQ_Data\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12!\n" +
	"\fserver_nonce\x18\x02 \x01(\fR\vserverNonce\x12\x0e\n" +
	"\x02pq\x18\x03 \x01(\tR\x02pq\x12C\n" +
	"\x1eserver_public_key_fingerprints\x18\x04 \x03(\x03R\x1bserverPublicKeyFingerprints\"j\n" +
	"\x05ResPQ\x128\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x16.mtproto.TLConstructorR\vconstructor\x12'\n" +
	"\x04Data\x18\x02 \x01(\v2\x13.mtproto.ResPQ_DataR\x04Data\"3\n" +
	"\bTL_resPQ\x12'\n" +
	"\x04Data\x18\x02 \x01(\v2\x13.mtproto.ResPQ_DataR\x04Data\"\x97\x01\n" +
	"\x13P_Q_inner_data_Data\x12\x0e\n" +
	"\x02pq\x18\x01 \x01(\tR\x02pq\x12\f\n" +
	"\x01p\x18\x02 \x01(\tR\x01p\x12\f\n" +
	"\x01q\x18\x03 \x01(\tR\x01q\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\x12!\n" +
	"\fserver_nonce\x18\x05 \x01(\fR\vserverNonce\x12\x1b\n" +
	"\tnew_nonce\x18\x06 \x01(\fR\bnewNonce\"|\n" +
	"\x0eP_Q_inner_data\x128\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x16.mtproto.TLConstructorR\vconstructor\x120\n" +
	"\x04Data\x18\x02 \x01(\v2\x1c.mtproto.P_Q_inner_data_DataR\x04Data\"E\n" +
	"\x11TL_p_q_inner_data\x120\n" +
	"\x04Data\x18\x02 \x01(\v2\x1c.mtproto.P_Q_inner_data_DataR\x04DataB[\n" +
	"\x1fcom.takemakefake.engine.mtprotoB\aMTProtoH\x02Z-github.com/takemakefake/proto/mtproto;mtprotob\x06proto3"

var (
	file_schema_tl_handshake_proto_rawDescOnce sync.Once
	file_schema_tl_handshake_proto_rawDescData []byte
)

func file_schema_tl_handshake_proto_rawDescGZIP() []byte {
	file_schema_tl_handshake_proto_rawDescOnce.Do(func() {
		file_schema_tl_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_tl_handshake_proto_rawDesc), len(file_schema_tl_handshake_proto_rawDesc)))
	})
	return file_schema_tl_handshake_proto_rawDescData
}

var file_schema_tl_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_schema_tl_handshake_proto_goTypes = []any{
	(*Server_DH_Params_Data)(nil),         // 0: mtproto.Server_DH_Params_Data
	(*Server_DH_Params)(nil),              // 1: mtproto.Server_DH_Params
	(*TLServer_DHParamsFail)(nil),         // 2: mtproto.TL_server_DH_params_fail
	(*TLServer_DHParamsOk)(nil),           // 3: mtproto.TL_server_DH_params_ok
	(*Server_DHInnerData_Data)(nil),       // 4: mtproto.Server_DH_inner_data_Data
	(*Server_DHInnerData)(nil),            // 5: mtproto.Server_DH_inner_data
	(*TLServer_DHInnerData)(nil),          // 6: mtproto.TL_server_DH_inner_data
	(*Client_DH_Inner_Data_Data)(nil),     // 7: mtproto.Client_DH_Inner_Data_Data
	(*Client_DH_Inner_Data)(nil),          // 8: mtproto.Client_DH_Inner_Data
	(*TLClient_DHInnerData)(nil),          // 9: mtproto.TL_client_DH_inner_data
	(*SetClient_DHParamsAnswer_Data)(nil), // 10: mtproto.Set_client_DH_params_answer_Data
	(*SetClient_DHParamsAnswer)(nil),      // 11: mtproto.Set_client_DH_params_answer
	(*TLDhGenOk)(nil),                     // 12: mtproto.TL_dh_gen_ok
	(*TLDhGenRetry)(nil),                  // 13: mtproto.TL_dh_gen_retry
	(*TLDhGenFail)(nil),                   // 14: mtproto.TL_dh_gen_fail
	(*DestroyAuthKeyRes_Data)(nil),        // 15: mtproto.DestroyAuthKeyRes_Data
	(*DestroyAuthKeyRes)(nil),             // 16: mtproto.DestroyAuthKeyRes
	(*TLDestroyAuthKeyOk)(nil),            // 17: mtproto.TL_destroy_auth_key_ok
	(*TLDestroyAuthKeyNone)(nil),          // 18: mtproto.TL_destroy_auth_key_none
	(*TLDestroyAuthKeyFail)(nil),          // 19: mtproto.TL_destroy_auth_key_fail
	(*ResPQ_Data)(nil),                    // 20: mtproto.ResPQ_Data
	(*ResPQ)(nil),                         // 21: mtproto.ResPQ
	(*TLResPQ)(nil),                       // 22: mtproto.TL_resPQ
	(*P_QInnerData_Data)(nil),             // 23: mtproto.P_Q_inner_data_Data
	(*P_QInnerData)(nil),                  // 24: mtproto.P_Q_inner_data
	(*TLPQInnerData)(nil),                 // 25: mtproto.TL_p_q_inner_data
	(TLConstructor)(0),                    // 26: mtproto.TLConstructor
}
var file_schema_tl_handshake_proto_depIdxs = []int32{
	26, // 0: mtproto.Server_DH_Params.constructor:type_name -> mtproto.TLConstructor
	0,  // 1: mtproto.Server_DH_Params.Data:type_name -> mtproto.Server_DH_Params_Data
	0,  // 2: mtproto.TL_server_DH_params_fail.Data:type_name -> mtproto.Server_DH_Params_Data
	0,  // 3: mtproto.TL_server_DH_params_ok.Data:type_name -> mtproto.Server_DH_Params_Data
	26, // 4: mtproto.Server_DH_inner_data.constructor:type_name -> mtproto.TLConstructor
	4,  // 5: mtproto.Server_DH_inner_data.Data:type_name -> mtproto.Server_DH_inner_data_Data
	4,  // 6: mtproto.TL_server_DH_inner_data.Data:type_name -> mtproto.Server_DH_inner_data_Data
	26, // 7: mtproto.Client_DH_Inner_Data.constructor:type_name -> mtproto.TLConstructor
	7,  // 8: mtproto.Client_DH_Inner_Data.Data:type_name -> mtproto.Client_DH_Inner_Data_Data
	7,  // 9: mtproto.TL_client_DH_inner_data.Data:type_name -> mtproto.Client_DH_Inner_Data_Data
	26, // 10: mtproto.Set_client_DH_params_answer.constructor:type_name -> mtproto.TLConstructor
	10, // 11: mtproto.Set_client_DH_params_answer.Data:type_name -> mtproto.Set_client_DH_params_answer_Data
	10, // 12: mtproto.TL_dh_gen_ok.Data:type_name -> mtproto.Set_client_DH_params_answer_Data
	10, // 13: mtproto.TL_dh_gen_retry.Data:type_name -> mtproto.Set_client_DH_params_answer_Data
	10, // 14: mtproto.TL_dh_gen_fail.Data:type_name -> mtproto.Set_client_DH_params_answer_Data
	26, // 15: mtproto.DestroyAuthKeyRes.constructor:type_name -> mtproto.TLConstructor
	15, // 16: mtproto.DestroyAuthKeyRes.Data:type_name -> mtproto.DestroyAuthKeyRes_Data
	15, // 17: mtproto.TL_destroy_auth_key_ok.Data:type_name -> mtproto.DestroyAuthKeyRes_Data
	15, // 18: mtproto.TL_destroy_auth_key_none.Data:type_name -> mtproto.DestroyAuthKeyRes_Data
	15, // 19: mtproto.TL_destroy_auth_key_fail.Data:type_name -> mtproto.DestroyAuthKeyRes_Data
	26, // 20: mtproto.ResPQ.constructor:type_name -> mtproto.TLConstructor
	20, // 21: mtproto.ResPQ.Data:type_name -> mtproto.ResPQ_Data
	20, // 22: mtproto.TL_resPQ.Data:type_name -> mtproto.ResPQ_Data
	26, // 23: mtproto.P_Q_inner_data.constructor:type_name -> mtproto.TLConstructor
	23, // 24: mtproto.P_Q_inner_data.Data:type_name -> mtproto.P_Q_inner_data_Data
	23, // 25: mtproto.TL_p_q_inner_data.Data:type_name -> mtproto.P_Q_inner_data_Data
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_schema_tl_handshake_proto_init() }
func file_schema_tl_handshake_proto_init() {
	if File_schema_tl_handshake_proto != nil {
		return
	}
	file_schema_tl_crc32_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_tl_handshake_proto_rawDesc), len(file_schema_tl_handshake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_tl_handshake_proto_goTypes,
		DependencyIndexes: file_schema_tl_handshake_proto_depIdxs,
		MessageInfos:      file_schema_tl_handshake_proto_msgTypes,
	}.Build()
	File_schema_tl_handshake_proto = out.File
	file_schema_tl_handshake_proto_goTypes = nil
	file_schema_tl_handshake_proto_depIdxs = nil
}
