//
// WARNING! All changes made in this file will be lost!
// Created from 'scheme.tl' by 'codegen_proto.py'
//
//  Copyright (c) 2017, https://github.com/xxxxx
//  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: schema.tl.transport_service.proto

package mtproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// /////////////////////////////////////////////////////////////////////////////
// rpc_drop_answer#58e4a740 req_msg_id:long = RpcDropAnswer;
type TLRpcDropAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqMsgId      int64                  `protobuf:"varint,1,opt,name=req_msg_id,json=reqMsgId,proto3" json:"req_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLRpcDropAnswer) Reset() {
	*x = TLRpcDropAnswer{}
	mi := &file_schema_tl_transport_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLRpcDropAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLRpcDropAnswer) ProtoMessage() {}

func (x *TLRpcDropAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_transport_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLRpcDropAnswer.ProtoReflect.Descriptor instead.
func (*TLRpcDropAnswer) Descriptor() ([]byte, []int) {
	return file_schema_tl_transport_service_proto_rawDescGZIP(), []int{0}
}

func (x *TLRpcDropAnswer) GetReqMsgId() int64 {
	if x != nil {
		return x.ReqMsgId
	}
	return 0
}

// /////////////////////////////////////////////////////////////////////////////
// get_future_salts#b921bd04 num:int = FutureSalts;
type TLGetFutureSalts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int32                  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLGetFutureSalts) Reset() {
	*x = TLGetFutureSalts{}
	mi := &file_schema_tl_transport_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLGetFutureSalts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLGetFutureSalts) ProtoMessage() {}

func (x *TLGetFutureSalts) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_transport_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLGetFutureSalts.ProtoReflect.Descriptor instead.
func (*TLGetFutureSalts) Descriptor() ([]byte, []int) {
	return file_schema_tl_transport_service_proto_rawDescGZIP(), []int{1}
}

func (x *TLGetFutureSalts) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// /////////////////////////////////////////////////////////////////////////////
// ping#7abe77ec ping_id:long = Pong;
type TLPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PingId        int64                  `protobuf:"varint,1,opt,name=ping_id,json=pingId,proto3" json:"ping_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLPing) Reset() {
	*x = TLPing{}
	mi := &file_schema_tl_transport_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLPing) ProtoMessage() {}

func (x *TLPing) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_transport_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLPing.ProtoReflect.Descriptor instead.
func (*TLPing) Descriptor() ([]byte, []int) {
	return file_schema_tl_transport_service_proto_rawDescGZIP(), []int{2}
}

func (x *TLPing) GetPingId() int64 {
	if x != nil {
		return x.PingId
	}
	return 0
}

// /////////////////////////////////////////////////////////////////////////////
// ping_delay_disconnect#f3427b8c ping_id:long disconnect_delay:int = Pong;
type TLPingDelayDisconnect struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PingId          int64                  `protobuf:"varint,1,opt,name=ping_id,json=pingId,proto3" json:"ping_id,omitempty"`
	DisconnectDelay int32                  `protobuf:"varint,2,opt,name=disconnect_delay,json=disconnectDelay,proto3" json:"disconnect_delay,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TLPingDelayDisconnect) Reset() {
	*x = TLPingDelayDisconnect{}
	mi := &file_schema_tl_transport_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLPingDelayDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLPingDelayDisconnect) ProtoMessage() {}

func (x *TLPingDelayDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_transport_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLPingDelayDisconnect.ProtoReflect.Descriptor instead.
func (*TLPingDelayDisconnect) Descriptor() ([]byte, []int) {
	return file_schema_tl_transport_service_proto_rawDescGZIP(), []int{3}
}

func (x *TLPingDelayDisconnect) GetPingId() int64 {
	if x != nil {
		return x.PingId
	}
	return 0
}

func (x *TLPingDelayDisconnect) GetDisconnectDelay() int32 {
	if x != nil {
		return x.DisconnectDelay
	}
	return 0
}

// /////////////////////////////////////////////////////////////////////////////
// destroy_session#e7512126 session_id:long = DestroySessionRes;
type TLDestroySession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLDestroySession) Reset() {
	*x = TLDestroySession{}
	mi := &file_schema_tl_transport_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLDestroySession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLDestroySession) ProtoMessage() {}

func (x *TLDestroySession) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_transport_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLDestroySession.ProtoReflect.Descriptor instead.
func (*TLDestroySession) Descriptor() ([]byte, []int) {
	return file_schema_tl_transport_service_proto_rawDescGZIP(), []int{4}
}

func (x *TLDestroySession) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

// /////////////////////////////////////////////////////////////////////////////
// contest.saveDeveloperInfo#9a5f6e95 vk_id:int name:string phone_number:string age:int city:string = Bool;
type TLContestSaveDeveloperInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VkId          int32                  `protobuf:"varint,1,opt,name=vk_id,json=vkId,proto3" json:"vk_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLContestSaveDeveloperInfo) Reset() {
	*x = TLContestSaveDeveloperInfo{}
	mi := &file_schema_tl_transport_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLContestSaveDeveloperInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLContestSaveDeveloperInfo) ProtoMessage() {}

func (x *TLContestSaveDeveloperInfo) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_transport_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLContestSaveDeveloperInfo.ProtoReflect.Descriptor instead.
func (*TLContestSaveDeveloperInfo) Descriptor() ([]byte, []int) {
	return file_schema_tl_transport_service_proto_rawDescGZIP(), []int{5}
}

func (x *TLContestSaveDeveloperInfo) GetVkId() int32 {
	if x != nil {
		return x.VkId
	}
	return 0
}

func (x *TLContestSaveDeveloperInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TLContestSaveDeveloperInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *TLContestSaveDeveloperInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *TLContestSaveDeveloperInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

var File_schema_tl_transport_service_proto protoreflect.FileDescriptor

const file_schema_tl_transport_service_proto_rawDesc = "" +
	"\n" +
	"!schema.tl.transport_service.proto\x12\amtproto\"2\n" +
	"\x12TL_rpc_drop_answer\x12\x1c\n" +
	"\n" +
	"req_msg_id\x18\x01 \x01(\x03R\breqMsgId\"'\n" +
	"\x13TL_get_future_salts\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x05R\x03num\"\"\n" +
	"\aTL_ping\x12\x17\n" +
	"\aping_id\x18\x01 \x01(\x03R\x06pingId\"^\n" +
	"\x18TL_ping_delay_disconnect\x12\x17\n" +
	"\aping_id\x18\x01 \x01(\x03R\x06pingId\x12)\n" +
	"\x10disconnect_delay\x18\x02 \x01(\x05R\x0fdisconnectDelay\"3\n" +
	"\x12TL_destroy_session\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\"\x90\x01\n" +
	"\x1cTL_contest_saveDeveloperInfo\x12\x13\n" +
	"\x05vk_id\x18\x01 \x01(\x05R\x04vkId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04cityB[\n" +
	"\x1fcom.takemakefake.engine.mtprotoB\aMTProtoH\x02Z-github.com/takemakefake/proto/mtproto;mtprotob\x06proto3"

var (
	file_schema_tl_transport_service_proto_rawDescOnce sync.Once
	file_schema_tl_transport_service_proto_rawDescData []byte
)

func file_schema_tl_transport_service_proto_rawDescGZIP() []byte {
	file_schema_tl_transport_service_proto_rawDescOnce.Do(func() {
		file_schema_tl_transport_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_tl_transport_service_proto_rawDesc), len(file_schema_tl_transport_service_proto_rawDesc)))
	})
	return file_schema_tl_transport_service_proto_rawDescData
}

var file_schema_tl_transport_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_schema_tl_transport_service_proto_goTypes = []any{
	(*TLRpcDropAnswer)(nil),            // 0: mtproto.TL_rpc_drop_answer
	(*TLGetFutureSalts)(nil),           // 1: mtproto.TL_get_future_salts
	(*TLPing)(nil),                     // 2: mtproto.TL_ping
	(*TLPingDelayDisconnect)(nil),      // 3: mtproto.TL_ping_delay_disconnect
	(*TLDestroySession)(nil),           // 4: mtproto.TL_destroy_session
	(*TLContestSaveDeveloperInfo)(nil), // 5: mtproto.TL_contest_saveDeveloperInfo
}
var file_schema_tl_transport_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_tl_transport_service_proto_init() }
func file_schema_tl_transport_service_proto_init() {
	if File_schema_tl_transport_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_tl_transport_service_proto_rawDesc), len(file_schema_tl_transport_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_tl_transport_service_proto_goTypes,
		DependencyIndexes: file_schema_tl_transport_service_proto_depIdxs,
		MessageInfos:      file_schema_tl_transport_service_proto_msgTypes,
	}.Build()
	File_schema_tl_transport_service_proto = out.File
	file_schema_tl_transport_service_proto_goTypes = nil
	file_schema_tl_transport_service_proto_depIdxs = nil
}
